DROP TABLE IF EXISTS BOOK;
  
CREATE TABLE BOOK(
 id INT AUTO_INCREMENT  PRIMARY KEY,
 title VARCHAR(250) NOT NULL,
 author VARCHAR(250) NOT NULL,
 active TINYINT(1) DEFAULT 1,
 create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);